version: "3.8"

services:

  product-intelligence-platform:
    build:
      context: .
      dockerfile: deployment/Dockerfile

    container_name: product_ai_platform

    ports:
      - "5000:5000"

    volumes:
      - .:/app

    environment:
      - FLASK_ENV=development

    restart: always